# Generated by Django 2.1.7 on 2019-04-16 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import manageportal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('discount', models.IntegerField(default=10)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_quantity_used', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('event_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('photo', models.ImageField(unique=True, upload_to=manageportal.models.get_upload_path)),
                ('shipping_cost', models.FloatField(default=0.0)),
                ('vat', models.FloatField(blank=True, default=0.0, null=True)),
                ('details', models.TextField()),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=manageportal.models.change_path)),
                ('status', models.CharField(default='Waiting', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular request across whole system')),
                ('money_paid', models.FloatField(default=0.0)),
                ('money_made', models.FloatField(default=0.0)),
                ('shipping_cost', models.FloatField(default=0.0)),
                ('vat', models.FloatField(default=0.0)),
                ('done_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageportal.Message')),
            ],
        ),
        migrations.AddField(
            model_name='coupons',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageportal.FeatureProducts'),
        ),
    ]
