# Generated by Django 2.2.1 on 2019-08-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageportal', '0003_auto_20190708_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uid',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
