# Generated by Django 2.2.5 on 2019-09-30 12:18

from django.db import migrations, models
import django.db.models.deletion
import manageportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageportal', '0004_transaction_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='MessageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=manageportal.models.change_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manageportal.Message')),
            ],
        ),
    ]
